SET FOREIGN_KEY_CHECKS=0;
truncate table item;
truncate table item_category;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO item_category(`id`,`name`)VALUES
(1,'vegetable'),
(2,'herb'),
(3,'house'),
(4,'succulent'),
(5,'fruit');


INSERT INTO `item`(`id`,`item_category_id`,`name`,`description`) VALUES
(1,1,"Tomato","Kamatis is a hairy annual herb, typically growing 1 to 3 meters in height, with ascending or spreading hairy and branched stems. Stem is weak, often sprawling over the ground or vines over other plants. Leaves are pinnate and alternate, oblong-ovate, 10 to 40 centimeters long. Leaflets are irregular and toothed or lobed. Inflorescence is racemose or cymose, 5 to 8 centimeters long, and few flowered. Flowers are yellow, 1 to 1.5 centimeters long. Fruit is variable in shape; in the wild and naturalized forms it is rounded or pear-shaped; 1 to 1.5 centimeters in diameter; in the commonly cultivated form, the fruit is rounded and compressed, lobed, 4 to 10 centimeters wide, red when ripe, smooth, fleshy, juicy, subacid, containing numerous seeds."),
(2,1,"Carrot","Carrot is an erect, vegetable herb, growing 30 to 60 centimeters in height, with 2 to 3 pinnate leaves, the ultimate leaflet being oblong-lanceolate or linear. Flowers are small, white, or yellow, borne in compound umbels. Fruit is small, ellipsoid, dorsally compressed, bristled and ribbed. The tap root is robust, sometimes swollen, fleshy, and yellow or orange-colored."),
(3,1,"Potato","Patatas is a perennial herb with rough, pinnate leaves. Flowers are rather large, white or purple, star-shaped, and borne on compound inflorescences, 3 to 4 centimeters in diameter. Roots grow round and edible fleshy tubers"),
(4,1,"Spinach","New Zealand spinach is an annual, spreading herb growing to 50 centimeters high. . Leaves are succulent, triangular to oval in shape, 3 to 6 centimeters long and 2.5 to 4.5 centimeters wide. The flowers are small and yellowish green."),
(5,1,"Eggplant","Talong is a coarse, usually branched, prickly or unarmed, erect, half-woody plant, growing to a height of 0.5 to 1 meter. Leaves are ovate to oblong-ovate, 10 to 25 centimeters long, stellate-hairy beneath, and irregularly or shallowly lobed at the margins. Flowers are axillary, purplish, about 2.5 centimeters long. Fruit is fleshy, smooth, purple, up to 25 centimeters long, extremely variable in shape, round, oblong, or cylindric-oblong.");

INSERT INTO `item`(`id`,`item_category_id`,`name`,`description`) VALUES
(6,2,"Basil","Balanoy is an erect, branched branched, smooth, somewhat hairy, and very aromatic undershrub, growing 0.5 to 1.5 meters high. Leaves are simple, opposite, ovate to oblong-ovate, entire or slightly toothed, with acute tips and glandular spots on the lower surface. Flowers are pink or purplish and borne in racemes which are 8 to 15 centimeters long. Calyx of the individual flower or floret is strongly reflexed, the upper lobe round, the lower two narrowly lanceolate and acuminate, and the lateral ones ovate. Corolla bilabiate, exerted, and upper lip broader, subequally 4-fid, the lower lip entire. Petals pink or purplish, stamens exserted. Fruits are nutlets, smooth or somewhat rugose."),
(7,2,"Laurel","Laurel is an erect or spreading, more or less branched, herbaceous or half-woody plant, 1.5 meters or less in height. Leaves are ovate to oblong-ovate, 8 to 13 centimeters long, smooth, slightly drooping, with entire, undulate or wavy margins, with a pointed or blunt tip and a pointed base. Spikes are 15 to 30 centimeters long. Calyx is tubular, 8 to 10 millimeters long, covered with stalked, sticky glands. Corolla is bright red, tube is slender, about 2.5 centimeters long, and the spreading limb, about 3 centimeters in diameter."),
(8,2,"Indian Borage","Trichodesma indicum is an erect, spreading, branched, annual herb, about 50 centimeters in height. Leaves are stalkless, opposite, lanceolate, 2 to 8 centimeters long, pointed at the tip, and heart-shaped at the base; the upper surfaces clothed with stiff hairs arising from circular tubercles, the lower surfaces less densely villous. Flowers occur singly in the axils of the leaves. Calyx is green, hairy, and 1 to 1.3 centimeters long, with pointed lobes. Corolla is pale blue, with the limb about 1.5 centimeters in diameter, and the lobes pointed. Fruit is ellipsoid, and enclosed by the calyx. Nutlets are about 5 millimeters long, and rough on the inner surface."),
(9,2,"Celery","Kintsay is an erect herb, seldom growing over 30 centimeters in height. The Chinese variety has short stems. Leaves are pinnate, with large, deeply-lobed segments, on long petioles. Peduncles are short, less than 1 centimeter in length, and borne opposite the leaves. Flowers are borne in umbels, very small, and greenish white. Fruit is very small, with narrow ridges."),
(10,2,"Chives","Kuchai is a kind of leek, ranked-scented, green, growing 20 to 40 centimeters high. Bulbs are small, white and clustered. Leaves are green, grasslike, narrowly linear, flattish, 15 to 30 centimeters long, 3 to 6 millimeters wide. Umbel has a few to many white flowers. The perianth is bell-shaped. Fruits are on pedicels of 2 to 3 centimeters long, obovoid, 3-lobed, 5 to 7 millimeters in diameter. Seeds are black, depressed, globose or reniform, 2.5 to 3 milimeters in diameter. In the Philippines, the plant seldom flowers.");

INSERT INTO `item`(`id`,`item_category_id`,`name`,`description`) VALUES
(11,3,"African Violet","African violet care information guide: Belonging to the Saintpaulia Genus with many species. Growing conditions, possible problems, pictures and description. "),
(12,3,"Barberton Daisy","A flowering pot plant displaying striking flowers."),
(13,3,"Belladonna Lily","Also known as the naked lady because of the bare flower stalks that appear without leaves. "),
(14,3,"Blushing Bromeliad","An interesting species from the bromeliad family which produces a red center within the rosette of leaves. "),
(15,3,"Beach Spider Lily","This amazing bulb based plant beach spider lily enjoys environments that are downright aquatic and easy to maintain. ");

INSERT INTO `item`(`id`,`item_category_id`,`name`,`description`) VALUES
(16,4,"Echeveria","The crown jewels of the rosette-forming succulents, easy-care Echeveria come in a rainbow of colors and can be easily found at nurseries. Some of our top picks include rose-colored ‘Afterglow’, frilly-edged ‘Blue Curls’, deep purple ‘Black Prince’, and pearly lavender ‘Perle von Nurnberg’. All Echeveria perform splendidly in containers and grow well in garden beds in mild-summer areas."),
(17,4,"Sedum (Stonecrop)","These primarily low-growing succulents are excellent planted as ground covers, tucked between rocks in walls, and planted to trail over the edges of containers. Chartreuse Sedum ‘Angelina’ is particularly useful as a bright complement to grey-green Echeveria."),
(18,4,"Aeonium","The fleshy rosettes of aeonium come in a rainbow of colors—from lemon yellow (Aeonium ‘Sunburst’) to deep maroon (Aeonium ‘Zwartkp’)—and take little water to thrive. With their bold forms and upright growth habit, they’re a natural choice for accent plants in garden beds and containers."),
(19,4,"Agave","From towering tequila-producing blue agave (Agave tequiliana) to ornamental artichoke agave (Agave parriya), there’s a reason to find a place for one of these spiny specimens in any garden. Their architectural shapes are particularly stunning silhouetted against walls and hedges. Plant spine-free Agave attenuatta along pathways to avoid being poked."),
(20,4,"Dudleya","The fleshy rosettes of most Dudleya varieties are covered by a chalky powder giving them the appearance of being freshly dusted with powdered sugar. To keep the powder from washing off, grow varieties such as Dudleya birttonii in areas sheltered from heavy rain such as on sunny covered patios or on bright windowsills.");

INSERT INTO `item`(`id`,`item_category_id`,`name`,`description`) VALUES
(21,5,"Avocado","Avocado is a subtropical plant that can resist some frost, but not freezing. There are many varieties, but the one most commonly found in the grocery store is the Hass avocado. Technically, avocado is a berry. The fruit only ripens after it has been removed from the tree."),
(22,5,"Banana","Bananas are a tropical herb that only grow in areas that do not receive a frost like South Florida and Hawaii. The banana most often sold on grocery store shelves is the Cavendish variety. Many varieties are available for the home and greenhouse grower, including dwarf trees."),
(23,5,"Mango","Mangoes are a tropical tree that only grow in areas that are frost-free all year. These trees can get quite large, up to 100 feet tall, but are very tough plants that produce fruit from even young trees."),
(24,5,"Pear","One of the best-known pear varieties is the Bartlett pear, which is often seen on the grocery store shelves. When planting pear trees, be sure to research the variety first. Not all pear trees will be able to cross-pollinate each other. This varies depending on the specific variety."),
(25,5,"Peach","Peaches are another longtime favorite because of their sweet, juicy flesh. The trees need a winter chill to set fruit and properly grow new leaves and branches. This varies depending on the variety of peach being grown.");



SET FOREIGN_KEY_CHECKS=0;
truncate table wiki;
truncate table steps;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO `wiki`(`id`,`item_id`,`title`) VALUES
(1,1,"How to plant a tomato");

INSERT INTO `steps`(`id`,`step_num`,`wiki_id`,`count_days`,`title`,`content`) VALUES
(1,1,1,1,"1. Pick a Good Spot","Place pots where they’ll receive at least six hours of sun. If pots aren’t near a water source, make sure you can get a garden hose to them (or don’t mind lugging a watering can around), because tomatoes need steady moisture supply. Group pots together, but not so close that leaves rub against each other (that can help spread disease). Grouping pots helps shade the root zones of the plants in the inner pots, which can be helpful when plants are sitting on concrete or an asphalt driveway, both of which absorb and reflect heat."),
(1,1,2,10,"2. Find the Best Tomatoes for You","Our Tomato Chooser takes the guesswork out of discovering which tomatoes will work best for your garden. In general, determinate tomatoes tend to do better in pots, so look for those. It’s also possible to grow indeterminate tomatoes in containers, of course, as long as you provide enough support and soil volume. Speaking of which…."),
(1,1,3,15,"3. Choose the Right Pot","Those seedlings may look small now, but a full-grown tomato plant needs a lot of space for a strong root system. For maximum production, the ideal pot size is 18-inch diameter for determinate tomatoes and 24-inch diameter for indeterminate tomatoes. When using a fabric pot or other type sold by volume, aim for 20 gallons. It’s fine to use a smaller container, like a 5-gallon bucket or 10-gallon container, but for best results, stick with the smaller patio- or bush-type tomatoes (such as Better Bush, Bush Goliath, or Patio). Know, too, that tomatoes in smaller pots require more watering and feeding."),
(1,1,4,20,"4. Use Premium Quality Potting Soil","Garden soil from planting beds tends to be too heavy for containers — it will over-compact — and may contain disease organisms. Tomatoes are susceptible to diseases (such as blight) and pests (like nematodes) that can hang out in soil, and one advantage of growing in pots is that doing so can reduce outbreaks. Fill containers with premium quality potting soil, such as Miracle-Gro or Nature’s Care, for best results. Light and fluffy, it will provide the air and moisture circulation needed by your plants."),
(1,1,5,29,"5. Plant Tomatoes Properly","When growing tomatoes in containers, follow the usual instructions for planting Bonnie’s biodegradable pots. Be sure to dig a hole deep enough to cover two-thirds of the tomato stem to encourage more root growth. As a rule of thumb, wait to plant until after your area’s last frost date. If a chilly night threatens, cover pots with a frost blanket and swaddle them with blankets, straw, or burlap for extra protection. (Can’t wait to plant? Find out how to get an early start on growing tomatoes.)"),
(1,1,6,30,"6. Add Support","Insert a support when you plant each tomato, as doing so later on may disturb the growing roots. A traditional tomato cage or stake works well for determinate types. Use a string trellis, tall stake, tomato toutour, or sturdy cage for indeterminate tomatoes. To create your own tomato cages, bend metal fencing or hog wire into a cylindrical shape, then use wire to connect the ends. Insert it into the soil or slip it over the outside of the pot, then secure it to stakes driven firmly into the soil."),
(1,1,7,32,"7. Cover the Soil","When planting tomatoes in pots, keep the soil at least one inch below the pot rim, so you can add a layer of mulch to help keep soil moist. You can use traditional mulch materials, like straw, shredded bark, chopped leaves, or newspaper (minus the glossy circulars). Paper decomposes quickly, especially in hottest regions, so plan to refresh the layer as needed during the growing season."),
(1,1,8,33,"8. Water Regularly","Proper watering is a big key to success for growing tomatoes in pots. Keep soil consistently moist, but not saturated. (Inconsistent moisture can pave the way to blossom end rot.) Use the finger test to see if a plant needs water: If the top inch of soil is dry when you push your finger into it, it’s time to give it a drink. (Plants larger than knee-high can require almost daily watering once summer heat arrives.) Place a saucer beneath each pot to catch water that runs through the soil, so plants can absorb that extra moisture over the course of a hot day. (It will also protect decks and patios.) A drip irrigation system can help reduce the time you spend holding the hose, and will pay for itself quickly if you’re raising a large crop of potted tomatoes. If you’re only tending a few pots, time spent watering provides an opportunity to inspect plants and keep an eye out for problems. When summer vacation beckons, line up someone to do the watering if you hope to still have tomatoes to pick upon your return."),
(1,1,9,44,,"9. Feed Your Plants","Mixing a continuous-release fertilizer into the soil helps get tomatoes off to a solid start. Then, use a liquid plant food, such as Bonnie Herb, Vegetable & Flower Plant Food, every week or so throughout the season (especially once flowers have begun to form). That may seem like a lot, but each watering washes nutrients out of the pot. As with all fertilizers, follow package instructions."),
(1,1,10,73,"10. Clean Up at Season’s End","Remove spent tomato plants from the pots at the end of the growing season. If you plan to use the same pots to grow anything in the tomato family (think tomatoes peppers, eggplants, potatoes) during the following season, you’ll want to start with fresh soil. Discard any remaining soil, wash and scrub soil from pots, then sterilize them by wiping or spraying with a solution of one part bleach to 10 parts water.");


