server:
  port: 8091
  contextPath: /api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comfarm?characterEncoding=utf8
    username: root
    password: 1234

#  jpa:
#    hibernate:
#      ddl-auto: create-drop

  cloud:
    config:
      discovery:
        enabled: true
flyway:
  baseline-on-migrate: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
endpoints:
  trace:
    sensitive: false
logging:
  level: TRACE
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF
#    server.tomcat.accesslog.enabled: true
#    server.tomcat.accessLogEnabled: true
#    springfox.documentation.swagger2: DEBUG
#    org.springframework.data: DEBUG
  file: logs/app.log

